### ISSUE TITLE
Leak?

### ISSUE THREAD

**Issue by RefuX** [bjornsallarp/BSForwardGeocoder#1]
If I run your demo app in Instruments with the Leaks option, every time I do a search I get leaks reported:
Leaked Object,# Address Size    Responsible Library Responsible Frame
Malloc 512 Bytes,   0x8897e00   512 Foundation  allocateCollectableUnscannedStorage

Leaked Object,# Address Size    Responsible Library Responsible Frame
Malloc 512 Bytes,   0x8864000   512 Foundation  allocateCollectableUnscannedStorage

Leaked Object,# Address Size    Responsible Library Responsible Frame
NSConcreteMapTable,     0x5b837d0   160 Foundation  +[NSMapTable alloc]

**Comment by bjornsallarp** [comment]
Use NSData to fetch data from Google instead of NSXMLParser which has a memory leak, more info http://bit.ly/h8iKeg. Closed by a65b6abc0869b256a66704be841b3ebec493086e

**Comment by bjornsallarp** [comment]
Thanks for the feedback! Not my leak but a workaround fixed it.

**Comment by RefuX** [comment]
Thanks workaround works perfectly :)
