### ISSUE TITLE
error: cannot find protocol declaration 'NSURLConnectionDataDelegate'

### ISSUE THREAD

**Issue by PavanMore** [bjornsallarp/BSForwardGeocoder#12]
I downloaded your code from github and try to  run then it will give following error.
Forward Geocoder/BSForwardGeocoder.h:44: error: cannot find protocol declaration for 'NSURLConnectionDataDelegate'

**Comment by bjornsallarp** [comment]
It is part of iOS5. You need to raise your deployment target
