### ISSUE TITLE
Status codes use HTTP codes not response field

### ISSUE THREAD

**Issue by jritzi** [bjornsallarp/BSForwardGeocoder#3]
In the [Geocoding API documentation](http://code.google.com/apis/maps/documentation/geocoding/), it says that the status of the request is returned in a "status" field in the response. However, BSForwardGeocoder appears to use HTTP status codes instead. It appears that that should be updated to use the "status" response field for the current API.

**Comment by bjornsallarp** [comment]
This is incorrect. The status field of the response is parsed and accessable through the "status" property of BSForwardGeocoder. There is also an enum in the .h file for the various response statuses. However, the requeste itself can fail (no internet connection etc), which will call the failed methods of the delegate protocol. If the request is successful you still need to check the status of the response and handle it accordingly.

**Comment by jritzi** [comment]
Ah, I see. I saw the enum values in for `G_GEO_*` and assumed they were being matched against HTTP status codes. Thanks for the clarification.
