### ISSUE TITLE
Overlapping requests?

### ISSUE THREAD

**Issue by jritzi** [bjornsallarp/BSForwardGeocoder#4]
This may not be an issue, but how does BSForwardGeocoder handle overlapping requests (i.e. a call to `findLocation:` before a previous call has finished)? It seems like this could cause inconsistent results because the threads are sharing instance variables.

**Comment by bjornsallarp** [comment]
It doesn't handle overlapping requests, so you are correct, it could return inconsistent results if called multiple times. You will have to prevent searching more than once in your UI. You are free to fork my project and add functionality for handling overlapping requests if you wish. I'll be happy to include it.

**Comment by jritzi** [comment]
Alright thanks. If I have some extra time I will.

**Comment by jritzi** [comment]
I don't think I'll be able to take care of this one (the multi-threading involved is a little over my head), so I'll look at handling it in my UI.

**Comment by HardyMacia** [comment]
His code doesn't handle it correctly at all. The simple solution is to create a new instance of the ForwardGeocoder for each new lookup you want to do.

**Comment by bjornsallarp** [comment]
I disagree with not handling it correctly, it's designed to do one lookup at the time. It mimics MKReveseGeocoder

**Comment by jritzi** [comment]
I don't think it necessarily needs to, but I think this should be well-documented so people don't misunderstand how it's supposed to be used.
