### ISSUE TITLE
URL encoding not complete

### ISSUE THREAD

**Issue by jritzi** [bjornsallarp/BSForwardGeocoder#6]
The `-stringByAddingPercentEscapesUsingEncoding:` method BSForwardGeocoder is using does not escape all special characters (see [here](http://simonwoodside.com/weblog/2009/4/22/how_to_really_url_encode/)), like ampersands or slashes. Instead of formatting the URL and running the whole thing through that method, each parameter should be escaped individually using `CFURLCreateStringByAddingPercentEscapes`.

I'll submit a patch if I get a chance.

**Comment by jritzi** [comment]
Created pull request #7 for this.

**Comment by bjornsallarp** [comment]
Thanks! Pulled now
