### ISSUE TITLE
Context info would be nice

### ISSUE THREAD

**Issue by eimantas** [bjornsallarp/BSForwardGeocoder#9]
I'm creating an app where user need to create a route. I have my own wrapper for a location and use your awesome wrapper for forward geocoding addresses to coordinates. Unfortunately, when either of route endpoints are chose, I can't figure out which endpoint was chosen for forward geocoding.

Could there be some context info for finding location? something like this:

[_forwardGeocoder findLocation:locationString context:myContext];

the second param I imagine should be either NSDictionary or (void *)

**Comment by bjornsallarp** [comment]
The new version has blocks support which make context info superflous
